# Generated by Django 2.2.6 on 2019-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('nameoriginal', models.CharField(max_length=200, verbose_name='Оригинальное название')),
                ('have', models.BooleanField(verbose_name='Наличие игры')),
                ('min_player', models.IntegerField()),
                ('max_player', models.IntegerField()),
                ('disc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
